/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "sislog.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

Resultado *
inicializar_sislog_1(faclevel *argp, CLIENT *clnt)
{
	static Resultado clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, inicializar_sislog,
		(xdrproc_t) xdr_faclevel, (caddr_t) argp,
		(xdrproc_t) xdr_Resultado, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Resultado *
registrar_evento_1(eventsislog *argp, CLIENT *clnt)
{
	static Resultado clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, registrar_evento,
		(xdrproc_t) xdr_eventsislog, (caddr_t) argp,
		(xdrproc_t) xdr_Resultado, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Resultado *
obtener_total_facilidad_1(int *argp, CLIENT *clnt)
{
	static Resultado clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, obtener_total_facilidad,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_Resultado, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Resultado *
obtener_total_nivel_1(int *argp, CLIENT *clnt)
{
	static Resultado clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, obtener_total_nivel,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_Resultado, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Resultado *
obtener_total_facilidadnivel_1(faclevel *argp, CLIENT *clnt)
{
	static Resultado clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, obtener_total_facilidadnivel,
		(xdrproc_t) xdr_faclevel, (caddr_t) argp,
		(xdrproc_t) xdr_Resultado, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Resultado *
obtener_num_facilidades_1(void *argp, CLIENT *clnt)
{
	static Resultado clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, obtener_num_facilidades,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_Resultado, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Resultado *
obtener_num_niveles_1(void *argp, CLIENT *clnt)
{
	static Resultado clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, obtener_num_niveles,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_Resultado, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Resultado *
obtener_nombre_facilidad_1(int *argp, CLIENT *clnt)
{
	static Resultado clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, obtener_nombre_facilidad,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_Resultado, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Resultado *
obtener_nombre_nivel_1(int *argp, CLIENT *clnt)
{
	static Resultado clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, obtener_nombre_nivel,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_Resultado, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
