/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "sislog.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
sislog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		faclevel inicializar_sislog_1_arg;
		eventsislog registrar_evento_1_arg;
		int obtener_total_facilidad_1_arg;
		int obtener_total_nivel_1_arg;
		faclevel obtener_total_facilidadnivel_1_arg;
		int obtener_nombre_facilidad_1_arg;
		int obtener_nombre_nivel_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case inicializar_sislog:
		_xdr_argument = (xdrproc_t) xdr_faclevel;
		_xdr_result = (xdrproc_t) xdr_Resultado;
		local = (char *(*)(char *, struct svc_req *)) inicializar_sislog_1_svc;
		break;

	case registrar_evento:
		_xdr_argument = (xdrproc_t) xdr_eventsislog;
		_xdr_result = (xdrproc_t) xdr_Resultado;
		local = (char *(*)(char *, struct svc_req *)) registrar_evento_1_svc;
		break;

	case obtener_total_facilidad:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_Resultado;
		local = (char *(*)(char *, struct svc_req *)) obtener_total_facilidad_1_svc;
		break;

	case obtener_total_nivel:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_Resultado;
		local = (char *(*)(char *, struct svc_req *)) obtener_total_nivel_1_svc;
		break;

	case obtener_total_facilidadnivel:
		_xdr_argument = (xdrproc_t) xdr_faclevel;
		_xdr_result = (xdrproc_t) xdr_Resultado;
		local = (char *(*)(char *, struct svc_req *)) obtener_total_facilidadnivel_1_svc;
		break;

	case obtener_num_facilidades:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_Resultado;
		local = (char *(*)(char *, struct svc_req *)) obtener_num_facilidades_1_svc;
		break;

	case obtener_num_niveles:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_Resultado;
		local = (char *(*)(char *, struct svc_req *)) obtener_num_niveles_1_svc;
		break;

	case obtener_nombre_facilidad:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_Resultado;
		local = (char *(*)(char *, struct svc_req *)) obtener_nombre_facilidad_1_svc;
		break;

	case obtener_nombre_nivel:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_Resultado;
		local = (char *(*)(char *, struct svc_req *)) obtener_nombre_nivel_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (SISLOG, PRIMERA);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, SISLOG, PRIMERA, sislog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (SISLOG, PRIMERA, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, SISLOG, PRIMERA, sislog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (SISLOG, PRIMERA, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
