/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SISLOG_H_RPCGEN
#define _SISLOG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXFACILITIES 10
#define MAXLEVELS 8
#define MAXMSG 1024

typedef char *texto;

struct eventsislog {
	int facilidad;
	int nivel;
	texto msg;
};
typedef struct eventsislog eventsislog;

struct faclevel {
	int facilidad;
	int nivel;
};
typedef struct faclevel faclevel;

struct Resultado {
	int caso;
	union {
		int valor;
		texto msg;
	} Resultado_u;
};
typedef struct Resultado Resultado;

#define SISLOG 0x2022f001
#define PRIMERA 1

#if defined(__STDC__) || defined(__cplusplus)
#define inicializar_sislog 1
extern  Resultado * inicializar_sislog_1(faclevel *, CLIENT *);
extern  Resultado * inicializar_sislog_1_svc(faclevel *, struct svc_req *);
#define registrar_evento 2
extern  Resultado * registrar_evento_1(eventsislog *, CLIENT *);
extern  Resultado * registrar_evento_1_svc(eventsislog *, struct svc_req *);
#define obtener_total_facilidad 3
extern  Resultado * obtener_total_facilidad_1(int *, CLIENT *);
extern  Resultado * obtener_total_facilidad_1_svc(int *, struct svc_req *);
#define obtener_total_nivel 4
extern  Resultado * obtener_total_nivel_1(int *, CLIENT *);
extern  Resultado * obtener_total_nivel_1_svc(int *, struct svc_req *);
#define obtener_total_facilidadnivel 5
extern  Resultado * obtener_total_facilidadnivel_1(faclevel *, CLIENT *);
extern  Resultado * obtener_total_facilidadnivel_1_svc(faclevel *, struct svc_req *);
#define obtener_num_facilidades 6
extern  Resultado * obtener_num_facilidades_1(void *, CLIENT *);
extern  Resultado * obtener_num_facilidades_1_svc(void *, struct svc_req *);
#define obtener_num_niveles 7
extern  Resultado * obtener_num_niveles_1(void *, CLIENT *);
extern  Resultado * obtener_num_niveles_1_svc(void *, struct svc_req *);
#define obtener_nombre_facilidad 8
extern  Resultado * obtener_nombre_facilidad_1(int *, CLIENT *);
extern  Resultado * obtener_nombre_facilidad_1_svc(int *, struct svc_req *);
#define obtener_nombre_nivel 9
extern  Resultado * obtener_nombre_nivel_1(int *, CLIENT *);
extern  Resultado * obtener_nombre_nivel_1_svc(int *, struct svc_req *);
extern int sislog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define inicializar_sislog 1
extern  Resultado * inicializar_sislog_1();
extern  Resultado * inicializar_sislog_1_svc();
#define registrar_evento 2
extern  Resultado * registrar_evento_1();
extern  Resultado * registrar_evento_1_svc();
#define obtener_total_facilidad 3
extern  Resultado * obtener_total_facilidad_1();
extern  Resultado * obtener_total_facilidad_1_svc();
#define obtener_total_nivel 4
extern  Resultado * obtener_total_nivel_1();
extern  Resultado * obtener_total_nivel_1_svc();
#define obtener_total_facilidadnivel 5
extern  Resultado * obtener_total_facilidadnivel_1();
extern  Resultado * obtener_total_facilidadnivel_1_svc();
#define obtener_num_facilidades 6
extern  Resultado * obtener_num_facilidades_1();
extern  Resultado * obtener_num_facilidades_1_svc();
#define obtener_num_niveles 7
extern  Resultado * obtener_num_niveles_1();
extern  Resultado * obtener_num_niveles_1_svc();
#define obtener_nombre_facilidad 8
extern  Resultado * obtener_nombre_facilidad_1();
extern  Resultado * obtener_nombre_facilidad_1_svc();
#define obtener_nombre_nivel 9
extern  Resultado * obtener_nombre_nivel_1();
extern  Resultado * obtener_nombre_nivel_1_svc();
extern int sislog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_texto (XDR *, texto*);
extern  bool_t xdr_eventsislog (XDR *, eventsislog*);
extern  bool_t xdr_faclevel (XDR *, faclevel*);
extern  bool_t xdr_Resultado (XDR *, Resultado*);

#else /* K&R C */
extern bool_t xdr_texto ();
extern bool_t xdr_eventsislog ();
extern bool_t xdr_faclevel ();
extern bool_t xdr_Resultado ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SISLOG_H_RPCGEN */
