CC=gcc
CFLAGS=-I. -pthread

all: sislog cliente

sislog: # A RELLENAR DEPENDENCIAS
	# A RELLENAR COMANDOS
	|
	|

cliente: # A RELLENAR DEPENDENCIAS
	# A RELLENAR COMANDOS
	|
	|


limpia:
	-rm *.o

cleanall: limpia
	-rm sislog cliente *.dat
